version: 2.1

jobs:
  sonar-scan:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: sudo npm install -g sonarqube-scanner
      - run:
          name: Run SonarQube scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=raymond_org_secure-payments-portal \
              -Dsonar.organization=raymond_org \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  test-sonar:
    jobs:
      - sonar-scan